### ISSUE TITLE
请问一下，panel调用panel的准确姿势是怎么样的呢

### ISSUE THREAD

**Issue by johnsneakers** [fkworld/cocos-game-framework#1]
比如: Apanel 里面有个逻辑需要更新Bpanel某个变量的值
请问准确姿势是怎么做

另外，框架写的很优美，新手的我一目了然，非常感谢

**Comment by fkworld** [comment]
多谢夸奖。

这个问题不局限于panel调用panel，而是属于脚本调用脚本。
简单点说，有2种方案：
- [其一是通过脚本唯一单例获取到另外一个脚本。我在[使用单例模式获取脚本运行实例](https://www.yuque.com/fengyong/game-develop-road/onnlub)中有比较细致的描述，可以参考。
- 其二是通过node.getComponent()来获取脚本组件。这种方法比较基础，新手使用起来逻辑比较合理，另外也适用于脚本实例不唯一的情况。比如有两个node上都挂载了脚本A，就需要使用这种方法来区别两个不同的脚本A实例。

针对Panel的建议：
考虑到Panel的唯一性，建议使用第1种方案来处理，即在Panel的onLoad()方法中定义`PanelName.ins=this`，在其他脚本中调用`PanelName.ins`即可获取脚本实例。
另外，在现在的框架中，可以写在onLoad()方法中，也可以写在on_open()方法中。

**Comment by johnsneakers** [comment]
@fkworld  谢谢，我选择第一种 ^_^  
另外，再请教一个问题：

我创建了一个用户信息管理类(MPlayer),  在初始化(AppMain)的时候拿到玩家信息(金币,钻石什么的）,init MPlayer,把玩家信息赋值进去。有了MPlayer, 我现在在给个页面panel里面都可以直接读取到玩家的金币信息，但是当MPlayer里面属性更新的时候， 那些页面并不会自己刷新数值。我查阅了一些资料，发现这种需求实现有各种不同方法，看的有点懵逼。
想请教一下，这种需求的最佳实践您认为怎么做比较好

**Comment by fkworld** [comment]
针对邮件中提到的问题：

> 我创建了一个用户信息管理类(MPlayer), 在初始化(AppMain)的时候拿到玩家信息(金币,钻石什么的）,init MPlayer,把玩家信息赋值进去。有了MPlayer, 我现在在给个页面panel里面都可以直接读取到玩家的金币信息，但是当MPlayer里面属性更新的时候， 那些页面并不会自己刷新数值。我查阅了一些资料，发现这种需求实现有各种不同方法，看的有点懵逼。想请教一下，这种需求的最佳实践您认为怎么做比较好

（附：通过邮件回复的我无法直接用邮件回复你，因为是github抄送给我的。）

这样的的需求可以分成不同的情况，也有不同的对应方式。先假设PanelA，实例PanelA.ins，一个刷新界面相关数据的方法update_value()。

2种不同的情况：
- 数据修改的发起者不是PanelA，例如PanelA是常驻在游戏中的UI，数据修改在游戏的其他模块。
- 数据修改的发起者是PanelA

3种不同的处理方案：
- 从MPlayer中分发调用，通过MPlayer中具体数据的setter函数，在数据发生变化时调用`PanelA.ins.update_value()`，一般还需要额外判定PanelA是否存在。
- 从发起者处调用，比如在PanelB中修改了MPlayer的数据，就在修改的位置调用`PanelA.ins.update_value()`
- 刷新式修改，即将数据变动写在PanelA的update()中，实际操作考虑性能会避免现在update()中，一般会通过cc.Component.schedule()方法写一个定时任务，0.5s\1s\2s刷新1次。

3种方案都可以使用，根据实际情况和个人喜好，并没有最佳实践，都各有优缺点。
我个人会在情况1+PanelA常驻的时候使用方案1，情况1+PanelA不常驻的时候使用方案2，情况2的时候使用方案2，没有延迟要求时使用方案3。
新手更推荐使用方案3，不在update()中性能损耗并不大，逻辑也比较集中（只在PanelA中处理，不会在其他脚本中处理PanelA的显示），延迟对绝大多数情况下也是可以接受的。如果延迟不可接受，再去考虑另外2种方案。

**Comment by johnsneakers** [comment]
@fkworld   非常感谢耐心回复，三种方案都很有启发性， 我目前使用的是第一种方案(删除问题是因为后来我实现了一个和你方案一差不多的)。现在可以基于你的提示优化一下。

另外，这两天用你这个框架有个疑惑，为什么关闭panel你都是destory掉， 而不是active=false. 看起来每次open读prefab应该没有active=true性能高吧？

**Comment by fkworld** [comment]
原因有2：
- 每次对node进行处理，可能会有一些遗留数据在node里面，多次打开关闭后可能会导致数据异常。而将node处理掉之后，每次针对prefab进行处理，则每次打开时都是初始化的数据，不存在任何数据异常的可能。
- 虽然每次cc.instance()有性能消耗，但是panel的个数是极少的，这个额外的性能消耗是可以接受的。

**Comment by johnsneakers** [comment]
> 原因有2：
> 
> * 每次对node进行处理，可能会有一些遗留数据在node里面，多次打开关闭后可能会导致数据异常。而将node处理掉之后，每次针对prefab进行处理，则每次打开时都是初始化的数据，不存在任何数据异常的可能。
> * 虽然每次cc.instance()有性能消耗，但是panel的个数是极少的，这个额外的性能消耗是可以接受的。

谢谢兄弟耐心回复， 收获很大。
