### ISSUE TITLE
FPanel.open的后面的参数怎么传？

### ISSUE THREAD

**Issue by IOXBruin** [fkworld/cocos-game-framework#19]
await FPanel.open(PanelLoading, {})
        await FPanel.close(PanelLoading, {})
        await FPanel.open(PanelGame, {})
看代码应该是传入一些动画效果，但是这个动画应该怎么写？
type ParamsPanelOpen<T extends typeof FPanel.FPanelTemplate> = Parameters<T["prototype"]["on_open"]>[0] extends undefined ? {} : Parameters<T["prototype"]["on_open"]>[0];
这个东西看的有点懵，不知道应该怎么做？望大神解答

**Comment by fkworld** [comment]
1. 传入的不是动画效果，传入的是对应 Panel 脚本的 on_open 函数的参数
2. 正在有计划的对这一部分进行修改，会以更加明显的逻辑表达传入打开参数

**Comment by IOXBruin** [comment]
谢谢大佬回复，其实后来看懂了。
我在open的参数里的 Params加了？变成可选参数。这样写await FPanel.open(PanelLoading)就不用写这个参数了。
panel的里面写on_open 函数就可以了

**Comment by fkworld** [comment]
可以，但是不建议这么做。因为可选参数会忽略那些必须填写参数的 panel。
